baseURL: "https://www.all-indonesia.com/"
title: All-Indonesia.com
theme: docsy
description : "Belajar & Tumbuh Bersama"
contentDir : "content/"

enableGitInfo: true
frontmatter:
  lastmod:
    - lastmod
    - :git
    - date
    - publishDate

minify:
  minifyOutput: true

enableRobotsTXT: true

taxonomies:
  tag: tags
  category: categories

googleAnalytics: G-7WQNTFN7YH

params:
  ShowShareButtons: true
  # github_repo: 'https://github.com/orezomi/all-indonesia.com'
  links:
    customLinks:
      - name: Sitemap
        url: /sitemap.xml
        desc: Sitemap
        target: _self
      - name: Disclaimer
        url: /disclaimer
        desc: Sitemap
        target: _self
      - name: Privacy Policy
        url: /privacy-policy
        desc: Privacy Policy
        target: _self
  offlineSearch: true
  offlineSearchMaxResults: 25
  offlineSearchSummaryLength: 200
  
  # katex:
  #   enable: true
  #   mhchem:
  #     enable: true
    # options:
    #   delimiters:
        # - left: $$
        #   right: $$
        #   display: true
        # - left: $
        #   right: $
        #   display: false
        # - left: \\(
        #   right: \\)
        #   display: false
        # - left: '\\['
        #   right: '\\]'
        #   display: true
  # mermaid:
  #   enable: true
  # plantuml:
  #   enable: true
  # markmap:
  #   enable: true
  # drawio:
  #   enable: false
  ui:
    sidebar_menu_compact: true
    sidebar_menu_foldable: false

  taxonomy:
    taxonomyCloud:
      - tags
      - categories
    taxonomyCloudTitle:
      - Tag Cloud
      - Categories
    taxonomyPageHeader:
      - tags
      - categories