baseURL: "https://www.all-indonesia.com/"
title: All-Indonesia.com
theme: docsy
description : "Info Rupa-Rupa"
contentDir : "content/"

minify:
  minifyOutput: true

enableRobotsTXT: true

taxonomies:
  tag: tags
  category: categories

params:
  ShowShareButtons: true
  links:
    customLinks:
      - name: Sitemap
        url: /sitemap.xml
        desc: Sitemap
        target: _self
      - name: Disclaimer
        url: /disclaimer
        desc: Sitemap
        target: _self
      - name: Privacy Policy
        url: /privacy-policy
        desc: Privacy Policy
        target: _self
  offlineSearch: true
  ui:
    sidebar_menu_compact: true
    sidebar_menu_foldable: false

  taxonomy:
    taxonomyCloud:
      - tags
      - categories
    taxonomyCloudTitle:
      - Tag Cloud
      - Categories
    taxonomyPageHeader:
      - tags
      - categories