baseURL: "https://www.all-indonesia.com/"
title: All-Indonesia.com
theme: docsy
description : "Info Rupa-Rupa"
contentDir : "content/"

minify:
  minifyOutput: true

enableRobotsTXT: true

taxonomies:
  tag: tags
  category: categories

params:
  ShowShareButtons: true
  offlineSearch: true
  ui:
    sidebar_menu_compact: true
    sidebar_menu_foldable: true

  taxonomy:
    taxonomyCloud:
      - tags
      - categories
    taxonomyCloudTitle:
      - Tag Cloud
      - Categories
    taxonomyPageHeader:
      - tags
      - categories